### ISSUE TITLE
Bad Data?

### ISSUE THREAD

**Issue by Mamonbo** [walfie/wanakana-rs#1]
Is that a typo?
https://github.com/walfie/wanakana-rs/blob/master/build.rs#L40

**Comment by Mamonbo** [comment]
No,that is the original behavior(wanakana.js) 😇 .

**Comment by walfie** [comment]
It looks like it's used for "Transform long vowels: 'オー' to 'おう'"

https://github.com/WaniKani/WanaKana/blob/7a4d6a815565e22db2b6f5321f926e38c17e962b/src/utils/katakanaToHiragana.js#L34
